export const COURSES = [
  'Computer Science',
  'Information Systems',
  'Information Security',
  'Business Analytics',
  'Business Administration',
  'Accountancy',
  'Engineering (Computer)',
  'Engineering (Electrical)',
  'Engineering (Mechanical)',
  'Engineering (Civil)',
  'Mathematics',
  'Physics',
  'Chemistry',
  'Biology',
  'Psychology',
  'Economics',
  'Law',
  'Medicine',
  'Nursing',
  'Architecture',
  'Design & Environment',
  'Arts & Social Sciences',
  'Music',
  'Other',
]

export const SKILLS = [

  { name: 'Python',            category: 'Academic' },
  { name: 'Java',              category: 'Academic' },
  { name: 'C++',               category: 'Academic' },
  { name: 'JavaScript',        category: 'Academic' },
  { name: 'Data Structures',   category: 'Academic' },
  { name: 'Machine Learning',  category: 'Academic' },
  { name: 'Calculus',          category: 'Academic' },
  { name: 'Statistics',        category: 'Academic' },
  { name: 'Linear Algebra',    category: 'Academic' },
  { name: 'Economics',         category: 'Academic' },
  { name: 'Accounting',        category: 'Academic' },
  { name: 'Finance',           category: 'Academic' },
  { name: 'Marketing',         category: 'Academic' },

  { name: 'Guitar',            category: 'Creative' },
  { name: 'Piano',             category: 'Creative' },
  { name: 'Singing',           category: 'Creative' },
  { name: 'Drawing',           category: 'Creative' },
  { name: 'Graphic Design',    category: 'Creative' },
  { name: 'UI/UX Design',      category: 'Creative' },
  { name: 'Photography',       category: 'Creative' },
  { name: 'Video Editing',     category: 'Creative' },

  { name: 'Fitness Training',  category: 'Lifestyle' },
  { name: 'Yoga',              category: 'Lifestyle' },
  { name: 'Cooking',           category: 'Lifestyle' },
  { name: 'Meditation',        category: 'Lifestyle' },

  { name: 'Mandarin',          category: 'Language' },
  { name: 'Japanese',          category: 'Language' },
  { name: 'Korean',            category: 'Language' },
  { name: 'Spanish',           category: 'Language' },
  { name: 'French',            category: 'Language' },
  { name: 'German',            category: 'Language' },
]

export const YEARS = [
  'Year 1',
  'Year 2',
  'Year 3',
  'Year 4',
  'Year 5+',
  'Graduate',
  'Exchange Student',
]